language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
before_install:
  - pip install setuptools --upgrade
  - pip install pip --upgrade
  - pip install --upgrade pytest>=3.6
  - pip install coveralls pytest-cov
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - which python
  - python --version
  - pytest --cov=pyOptimalEstimation
after_success:
- coveralls